### ISSUE TITLE
Config file for nginx

### ISSUE THREAD

**Issue by bazooka07** [YunoHost-Apps/pluxml_ynh#26]
Templates for configuring  Nginx with PluXml are stored at the following link :
http://wiki.pluxml.org/index.php?page=NGINX_PluXml

Feel free to ask some question in this forum :
http://forum.pluxml.org/viewtopic.php?id=5458
Mainly in french but english is understood.

Gracefully

**Comment by ewilly** [comment]
see pull request #31

**Comment by toitoinebzh** [comment]
thank you @ewilly , you solved this issue :+1:
