### ISSUE TITLE
YunoHost 3.0, Debian 9, dedicated php-fpm pool

### ISSUE THREAD

**Issue by M5oul** [YunoHost-Apps/pluxml_ynh#27]
PluXml is currently not working under YunoHost 3.0.

- a [decicated php-fpm is needed](https://github.com/YunoHost-Apps/freshrss_ynh/commit/44a5ea44c3d062e1ce13412765c3ff09911f80a6) (check if really needed).
- install missing php7 packages: sudo apt-get install php7.0-xml php7.0-gd
   - [found here](https://blog.norore.fr/index.php?article13/pluxml-nginx-et-php-7-sont-dans-un-bateau)

 Then, it work!

**Comment by Thatoo** [comment]
Is this issue still running? Should it not be closed?

**Comment by toitoinebzh** [comment]
This issue is outdated
