### ISSUE TITLE
Upgrade to 5.7 issue

### ISSUE THREAD

**Issue by ewilly** [YunoHost-Apps/pluxml_ynh#29]
`ynh_secure_remove ${final_path}/update # modif perso` give me an issue. After updating my previous instance i got a message is `file update/index.php not found`. A manual download the pluxml update directory and applying ownership solve the issue on my installation.

**Comment by toitoinebzh** [comment]
Hi @ewilly ,

Thank you for your feedback, I tried to reproduced you bug.
1- Install Pluxml 5.6 from an older commit : https://github.com/YunoHost-Apps/pluxml_ynh/tree/3c9860d5b46aa5027c146cfb15434ea23ff1ae71
2 - Upgrade to Pluxml 5.7 with the latest version https://github.com/YunoHost-Apps/pluxml_ynh/tree/f63bd012e4183fa4825fd65c970df040a5338ca7
3- Browse to https://domain.tld/pluxml/

The browser display "File not found" and the url is https://domain.tld/pluxml/update/index.php

Youl solved this issue by adding the directory "update" from Pluxml's website to "/var/www/pluxml" 
You are then able to complete the upgrade.

________________

I think I found the error. Pluxml recommend to remove the update directory and it was done automatically by the script. It should be done later, once the update is done.

**Comment by toitoinebzh** [comment]
This pull request will solve the problem
https://github.com/YunoHost-Apps/pluxml_ynh/pull/30
