### ISSUE TITLE
message d’erreur file not found

### ISSUE THREAD

**Issue by anto1ne** [YunoHost-Apps/pluxml_ynh#45]
Bug rapporté sur le forum

> [Problème](https://forum.yunohost.org/t/pluxml-blog-cms-sans-base-de-donnees-blog-cms-storing-data-in-xml/7158/18?u=ant0ine):
> 
> Après installation, dans l’interface utilisateur yunohost, on clique sur la case pluXml et cela ouvre une page chemin/install.php avec un message d’erreur file not found
>

**Comment by anto1ne** [comment]
@yalh76 apparemment le soucis existait avant la PR https://github.com/YunoHost-Apps/pluxml_ynh/pull/44

l'installation était sur un raspberry pi 3

**Comment by yalh76** [comment]
> 
> 
> @yalh76 apparemment le soucis existait avant la PR #44

Dans #44 je me suis juste contenté d'appliquer la dernière version de example_ynh sans regarder ce qui était fait par ailleurs: pour rendre le package un peu plus propre et qu'il passe level 7 sur Buster

J'ai pas regardé le post sur le forum, suis en vacances avec un accés limité, mais en premier abord, je dirais que l'étape https://github.com/YunoHost-Apps/pluxml_ynh/blob/f618522e430dfcb63e1a5843535cf0da165025f3/scripts/install#L94-L119

a pas dû bien se passer.

Le fichier `install.php` est supprimé une fois l'installation faite. https://github.com/YunoHost-Apps/pluxml_ynh/blob/f618522e430dfcb63e1a5843535cf0da165025f3/scripts/install#L121-L127

Donc si ça essaye d'aller sur la page `install.php` c'est que l’installation ne s'est pas bien passée... Je te laisse regarder les logs ;)

**Comment by anto1ne** [comment]
bon il semble que l'utilisateur s'en est sorti avec la dernière version issue de #44 
https://forum.yunohost.org/t/pluxml-blog-cms-sans-base-de-donnees-blog-cms-storing-data-in-xml/7158/20?u=ant0ine

je clos donc cette issue :)
